# Site settings
title:          Rui Costa's Blog
description:    "Rui Costa's blog"
baseurl:        ""
url:            "https://ruicosta.net"

# Author
author:
  name:         Rui Costa
  url:          https://ruicosta.net
  email:        rui.pfcosta@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
